### ISSUE TITLE
TypeError: Cannot get property "_path" of null

### ISSUE THREAD

**Issue by abdavid** [enonic/starter-headless#1]
Hi,

I am having some issues with the headless starter. 

Setup in XP and querying from GraphiQL works flawlessly, but problems arise when trying to query the api from outside the installation. 

I have been trying to dig around to see if I have overlooked any configuration but apart from the available documentation/demos I cannot see that I have overlooked anything. 

**Enonic XP version: 6.1.15**

This is the stacktrace;

```bash
WARN  graphql.execution.ExecutionStrategy - Exception while fetching data
com.enonic.xp.resource.ResourceProblemException: TypeError: Cannot get property "_path" of null
        at com.enonic.xp.resource.ResourceProblemException$Builder.build(ResourceProblemException.java:131)
        at com.enonic.xp.script.impl.util.ErrorHelper.doHandleException(ErrorHelper.java:54)
        at com.enonic.xp.script.impl.util.ErrorHelper.handleError(ErrorHelper.java:27)
        at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:41)
        at com.enonic.lib.graphql.GraphQlBean.lambda$setFieldData$4(GraphQlBean.java:206)
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:40)
        at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:87)
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
        at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
        at graphql.execution.Execution.executeOperation(Execution.java:58)
        at graphql.execution.Execution.execute(Execution.java:31)
        at graphql.GraphQL.execute(GraphQL.java:84)
        at graphql.GraphQL.execute(GraphQL.java:61)
        at com.enonic.lib.graphql.GraphQlBean.execute(GraphQlBean.java:258)
        at jdk.nashorn.internal.scripts.Script$Recompilation$330$2576AAA$graphql.L:1#execute(no.admin:/lib/graphql.js:76)
        at jdk.nashorn.internal.scripts.Script$Recompilation$329$1251A$graphql.L:1#post(no.admin:/services/graphql/graphql.js:41)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
```

**My fetch:**

_Preflight;_
```javascript
fetch("http://admin.local:8080/_/service/no.admin/graphql", {"credentials":"omit","headers":{},"referrer":"http://localhost:3000/35682497/pause","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"OPTIONS","mode":"cors"});
```

_Query;_
```javascript
fetch("http://admin.local:8080/_/service/no.admin/graphql", {"credentials":"omit","headers":{},"referrer":"http://localhost:3000/35682497/pause","referrerPolicy":"no-referrer-when-downgrade","body":"{\"operationName\":\"GetConfig\",\"variables\":{},\"query\":\"query GetConfig {\\n  guillotine {\\n    query(query: \\\"type='no.admin:merchant' AND ngram('_name', 'ap')\\\") {\\n      ... on no_admin_Merchant {\\n        data {\\n          pause {\\n            ... on no_admin_Pause {\\n              data {\\n                title\\n                text\\n                __typename\\n              }\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\"}","method":"POST","mode":"cors"});
```

Any response as to where I might start looking would be appreciated.

**Comment by abdavid** [comment]
vhost configuration is correct (I believe):

```bash
mapping.antichurn.host = admin.local
mapping.antichurn.source = /
mapping.antichurn.target = /portal/master/admin
mapping.antichurn.userStore = system
```

**Comment by sigdestad** [comment]
Hi David,
Your target mapping seems a bit weired? 
Is your site named "admin" ?

**Comment by sigdestad** [comment]
Also, did you publish your site yet?

**Comment by abdavid** [comment]
It is actually called antichurn admin. This installation would serve as a admin component to another installation. I just simplified the mapping a bit to match the fetches etc

the actual mapping is;

```
mapping.antichurn.host = admin.antichurn.local
mapping.antichurn.source = /
mapping.antichurn.target = /portal/master/antichurn
mapping.antichurn.userStore = system
```

**Comment by abdavid** [comment]
> Also, did you publish your site yet?

Content studio states that every thing is published

**Comment by sigdestad** [comment]
What permissions did you set for the content?
Does role "everyone" have read access to your content?

**Comment by abdavid** [comment]
> What permissions did you set for the content?
> Does role "everyone" have read access to your content?

Good pointer! Though even after I added anonymous reading access to the site (and verified it cascaded) the error still persists.

**Comment by sigdestad** [comment]
And you published the permission changes too I assume?

**Comment by abdavid** [comment]
> And you published the permission changes too I assume?

You are a saviour! I have been looking too hard at the code and not thinking that it could be permissions (doh). Allow me to buy you a beer at next JavaZone 👍

**Comment by abdavid** [comment]
Might want to add this to the doc though 😄 🥇

**Comment by sigdestad** [comment]
Indeed, you have also proven that there are potentials for improving the the error-handling in the API :-)
